FROM java:8

COPY target/bsvoorraadbeheer.jar bsvoorraadbeheer.jar

CMD java -Dserver.port=10009 -Deureka.client.service-url.defaultZone=http://$EUREKA_SERVER/eureka -Deureka.instance.prefer-ip-address=true -Deureka.instance.ip-address=$HOST_IP_ADRESS  -Deureka.instance.non-secure-port=$HOST_PORT -jar bsvoorraadbeheer.jar

EXPOSE 10009