server:
  port: 10009
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:10000/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
spring:
  application:
    name: bsvoorraadbeheer
  datasource:
    url: jdbc:mysql://localhost:3306/bsvoorraadbeheer
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop




