server:
  port: 10005
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:10000/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
spring:
  application:
    name: bsklantbeheer



